// <auto-generated />
namespace FTF.Storage.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddNotesToTag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNotesToTag));
        
        string IMigrationMetadata.Id
        {
            get { return "201612231601110_AddNotesToTag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
